### PR TITLE
Remove breadcrumb

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by dend** [comment]
@EdisonDa can you open an LSI to see why the build is failing here?

**Comment by TaraMeyer** [comment]
@EdisonDa - hello.  Have you had a chance to investigate the build failure?

**Comment by EdisonDa** [comment]
Is it still failed when we change the permission setting? See my comments in the this bug [126428](https://mseng.visualstudio.com/CSI/_workitems/edit/1264248). @TaraMeyer @dend

**Comment by sdwheeler** [comment]
Retriggering the build to see if it will complete now.

**Pull request merged**
