### PR TITLE
update new tile for LP

### PR DESCRIPTION
**Pull request by v-savila**
for bug 1085015

### CODE REVIEW

**Comment by v-savila** [comment]
#sign-off from apexprod
also need sign-off from zachal

**Comment by zjalexander** [comment]
@v-savila Is there a reason the module browser will be removed with this update? It's not a problem, but I'm curious if there's a limit on the number of tiles I can have on the Getting Started pivot.

**Comment by zjalexander** [comment]
looks good, thanks!

**Comment by v-savila** [comment]
#sign-off from apexprod
also need sign-off from zachal

**Comment by zjalexander** [comment]
sorry, did you need me to type the literal phrase #sign-off ?

**Comment by v-savila** [comment]
@zjalexander oh not necessarily, can you or someone on your team merge this PR then so I can resolve/close the bug?

**Comment by v-savila** [comment]
@v-tmeyer @sankethka can one of you merge this PR?

**Pull request merged**
